server:
  port: 8080

spring:
  application:
    name: kafka-producer
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

app:
  kafka:
    order:
      topic: orders-topic
